### ISSUE TITLE
Ontopreplica: doesn't open?

### ISSUE THREAD

**Issue by ValentinaSferragatta** [LorenzCK/OnTopReplica#115]
Hello everyone, I have been happily using OnTopReplica daily for a couple of months and I am so fond of it, but since yesterday when I try to launch the software it doesn't work. I have uninstalled and reinstalled it twice yesterday and today and also tried to fix the one I had with the patch here available but nothing. How can I do to fix this? A little disclaimer: I am not very good at programming and IT stuff, I can just execute things other people indicate to me... S.O.S.! Thank you very much, stay safe and have a good day :)

**Comment by VackerSimon** [comment]
Try this https://github.com/LorenzCK/OnTopReplica/issues/111#issuecomment-774975693

**Comment by LorenzCK** [comment]
Hello @ValentinaSferragatta, glad you find OnTopReplica useful! 😊 Like @VackerSimon suggested, try deleting the following directory:
`%USERPROFILE%\AppData\Local\Lorenz_Cuno_Klopfenstein`
which should reset the application completely.
