### ISSUE TITLE
Indicator for when window isn't up to date

### ISSUE THREAD

**Issue by jericjan** [LorenzCK/OnTopReplica#149]
I noticed that OnTopReplica will simply freeze when the window it's copying has been minimized. It would be nice to have some sort of indicator that tells the user that it has been minimized. Maybe dim the window or give it a bit of a tint.

**Comment by LorenzCK** [comment]
Hello @jericjan,
unfortunately this is currently impossible because of how OnTopReplica is implemented: the window “copy” is performed through DWM thumbnailing and there is no way (as far as I know) to detect whether the underlying window is being refreshed by the system or not.

**Comment by jericjan** [comment]
I see. That's a bit unfortunate. Before I found your app, I made clunkier version that used PrintWindow, and if a window was ever minimized, the preview would become a small rectangle that only contained the minimize, maximize, and close buttons of the copied window. Mine's much slower and CPU-intensive so I suppose better performance with DWM thumbnailing would be preferred, even if it does come at the cost of not knowing if it's up to date or not. 👍

**Comment by LorenzCK** [comment]
`PrintWindow` performs a full copy of the contents of a window, which gives you several advantages (you can decide how to _blit_ the contents on your own window, you can manipulate the pixels, etc.), all of which is not possible with DWM thumbnails (which perform a very lightweight copy within the window manager). One could monitor the source window and check whether it is minimized, non-visible, or has some other reason not to update itself, but it wouldn't be fully reliable I think.
