### ISSUE TITLE
Sadly it doesn't work with Neverwinter Nights

### ISSUE THREAD

**Issue by findell666** [LorenzCK/OnTopReplica#150]
Hello,
I tried to use OnTopReplica on top of GOG version of Neverwinter Nights 1, and it's not showing.
Is there something I can configure ?
thank you

**Comment by findell666** [comment]
It works when the game is windowed, but not in full screen.

**Comment by LorenzCK** [comment]
Hello @findell666: yes, the method used to ‘clone’ windows in OnTopReplica does not work with fullscreen applications. Adding this would require major work and OnTopReplica is currently not maintained anymore, unfortunately. :(

**Comment by findell666** [comment]
ok, I understand, thank you for the answer.
