### ISSUE TITLE
Забери свои чёртовы дампы

### ISSUE THREAD

**Issue by Wrascon** [LorenzCK/OnTopReplica#151]
Весь рабочий стол засрал мне ими.

![dumps](https://github.com/LorenzCK/OnTopReplica/assets/17739216/1d36e199-5bf5-4b3a-b54d-e5fa68f57a62)

[OnTopReplica-dump-202398-012.txt](https://github.com/LorenzCK/OnTopReplica/files/13853045/OnTopReplica-dump-202398-012.txt)
[OnTopReplica-dump-202411-31.txt](https://github.com/LorenzCK/OnTopReplica/files/13853046/OnTopReplica-dump-202411-31.txt)
[OnTopReplica-dump-202413-26.txt](https://github.com/LorenzCK/OnTopReplica/files/13853047/OnTopReplica-dump-202413-26.txt)
[OnTopReplica-dump-202414-156.txt](https://github.com/LorenzCK/OnTopReplica/files/13853048/OnTopReplica-dump-202414-156.txt)
[OnTopReplica-dump-202417-332.txt](https://github.com/LorenzCK/OnTopReplica/files/13853049/OnTopReplica-dump-202417-332.txt)
[OnTopReplica-dump-202417-1349.txt](https://github.com/LorenzCK/OnTopReplica/files/13853050/OnTopReplica-dump-202417-1349.txt)
[OnTopReplica-dump-2021114-216.txt](https://github.com/LorenzCK/OnTopReplica/files/13853051/OnTopReplica-dump-2021114-216.txt)
[OnTopReplica-dump-2021117-1937.txt](https://github.com/LorenzCK/OnTopReplica/files/13853052/OnTopReplica-dump-2021117-1937.txt)
[OnTopReplica-dump-2021118-36.txt](https://github.com/LorenzCK/OnTopReplica/files/13853053/OnTopReplica-dump-2021118-36.txt)
[OnTopReplica-dump-2021120-154.txt](https://github.com/LorenzCK/OnTopReplica/files/13853054/OnTopReplica-dump-2021120-154.txt)
[OnTopReplica-dump-2021123-1754.txt](https://github.com/LorenzCK/OnTopReplica/files/13853055/OnTopReplica-dump-2021123-1754.txt)
[OnTopReplica-dump-2021125-244.txt](https://github.com/LorenzCK/OnTopReplica/files/13853056/OnTopReplica-dump-2021125-244.txt)
[OnTopReplica-dump-2021129-031.txt](https://github.com/LorenzCK/OnTopReplica/files/13853057/OnTopReplica-dump-2021129-031.txt)
[OnTopReplica-dump-2021129-1952.txt](https://github.com/LorenzCK/OnTopReplica/files/13853058/OnTopReplica-dump-2021129-1952.txt)
[OnTopReplica-dump-2021129-2334.txt](https://github.com/LorenzCK/OnTopReplica/files/13853059/OnTopReplica-dump-2021129-2334.txt)
[OnTopReplica-dump-2021131-244.txt](https://github.com/LorenzCK/OnTopReplica/files/13853060/OnTopReplica-dump-2021131-244.txt)
[OnTopReplica-dump-2021210-2247.txt](https://github.com/LorenzCK/OnTopReplica/files/13853061/OnTopReplica-dump-2021210-2247.txt)
[OnTopReplica-dump-2021214-2116.txt](https://github.com/LorenzCK/OnTopReplica/files/13853062/OnTopReplica-dump-2021214-2116.txt)
[OnTopReplica-dump-2021214-2245.txt](https://github.com/LorenzCK/OnTopReplica/files/13853063/OnTopReplica-dump-2021214-2245.txt)
[OnTopReplica-dump-2021217-549.txt](https://github.com/LorenzCK/OnTopReplica/files/13853064/OnTopReplica-dump-2021217-549.txt)
[OnTopReplica-dump-2021218-439.txt](https://github.com/LorenzCK/OnTopReplica/files/13853065/OnTopReplica-dump-2021218-439.txt)
[OnTopReplica-dump-2021219-654.txt](https://github.com/LorenzCK/OnTopReplica/files/13853066/OnTopReplica-dump-2021219-654.txt)
[OnTopReplica-dump-2023112-135.txt](https://github.com/LorenzCK/OnTopReplica/files/13853067/OnTopReplica-dump-2023112-135.txt)
[OnTopReplica-dump-2023115-059.txt](https://github.com/LorenzCK/OnTopReplica/files/13853068/OnTopReplica-dump-2023115-059.txt)
[OnTopReplica-dump-2023116-222.txt](https://github.com/LorenzCK/OnTopReplica/files/13853069/OnTopReplica-dump-2023116-222.txt)
[OnTopReplica-dump-2023118-123.txt](https://github.com/LorenzCK/OnTopReplica/files/13853070/OnTopReplica-dump-2023118-123.txt)
[OnTopReplica-dump-2023717-2217.txt](https://github.com/LorenzCK/OnTopReplica/files/13853071/OnTopReplica-dump-2023717-2217.txt)
[OnTopReplica-dump-2023725-2115.txt](https://github.com/LorenzCK/OnTopReplica/files/13853072/OnTopReplica-dump-2023725-2115.txt)
[OnTopReplica-dump-2023727-2159.txt](https://github.com/LorenzCK/OnTopReplica/files/13853073/OnTopReplica-dump-2023727-2159.txt)
[OnTopReplica-dump-2023811-229.txt](https://github.com/LorenzCK/OnTopReplica/files/13853074/OnTopReplica-dump-2023811-229.txt)
[OnTopReplica-dump-2023812-02.txt](https://github.com/LorenzCK/OnTopReplica/files/13853075/OnTopReplica-dump-2023812-02.txt)
[OnTopReplica-dump-2023819-219.txt](https://github.com/LorenzCK/OnTopReplica/files/13853076/OnTopReplica-dump-2023819-219.txt)
[OnTopReplica-dump-2023822-919.txt](https://github.com/LorenzCK/OnTopReplica/files/13853077/OnTopReplica-dump-2023822-919.txt)
[OnTopReplica-dump-2023823-2356.txt](https://github.com/LorenzCK/OnTopReplica/files/13853078/OnTopReplica-dump-2023823-2356.txt)
[OnTopReplica-dump-2023825-180.txt](https://github.com/LorenzCK/OnTopReplica/files/13853079/OnTopReplica-dump-2023825-180.txt)
[OnTopReplica-dump-2023825-2235.txt](https://github.com/LorenzCK/OnTopReplica/files/13853081/OnTopReplica-dump-2023825-2235.txt)
[OnTopReplica-dump-2023829-040.txt](https://github.com/LorenzCK/OnTopReplica/files/13853082/OnTopReplica-dump-2023829-040.txt)
[OnTopReplica-dump-2023830-843.txt](https://github.com/LorenzCK/OnTopReplica/files/13853083/OnTopReplica-dump-2023830-843.txt)
[OnTopReplica-dump-2023831-255.txt](https://github.com/LorenzCK/OnTopReplica/files/13853084/OnTopReplica-dump-2023831-255.txt)
[OnTopReplica-dump-2023912-1832.txt](https://github.com/LorenzCK/OnTopReplica/files/13853085/OnTopReplica-dump-2023912-1832.txt)
[OnTopReplica-dump-2023913-1825.txt](https://github.com/LorenzCK/OnTopReplica/files/13853086/OnTopReplica-dump-2023913-1825.txt)
[OnTopReplica-dump-2023916-1453.txt](https://github.com/LorenzCK/OnTopReplica/files/13853087/OnTopReplica-dump-2023916-1453.txt)
[OnTopReplica-dump-2023918-1735.txt](https://github.com/LorenzCK/OnTopReplica/files/13853088/OnTopReplica-dump-2023918-1735.txt)
[OnTopReplica-dump-2023926-191.txt](https://github.com/LorenzCK/OnTopReplica/files/13853089/OnTopReplica-dump-2023926-191.txt)
[OnTopReplica-dump-2023926-196.txt](https://github.com/LorenzCK/OnTopReplica/files/13853090/OnTopReplica-dump-2023926-196.txt)
[OnTopReplica-dump-2023926-197.txt](https://github.com/LorenzCK/OnTopReplica/files/13853091/OnTopReplica-dump-2023926-197.txt)
[OnTopReplica-dump-2023927-1947.txt](https://github.com/LorenzCK/OnTopReplica/files/13853092/OnTopReplica-dump-2023927-1947.txt)
[OnTopReplica-dump-2023928-2353.txt](https://github.com/LorenzCK/OnTopReplica/files/13853093/OnTopReplica-dump-2023928-2353.txt)
[OnTopReplica-dump-20231011-17.txt](https://github.com/LorenzCK/OnTopReplica/files/13853094/OnTopReplica-dump-20231011-17.txt)
[OnTopReplica-dump-20231017-2310.txt](https://github.com/LorenzCK/OnTopReplica/files/13853095/OnTopReplica-dump-20231017-2310.txt)
[OnTopReplica-dump-20231025-1820.txt](https://github.com/LorenzCK/OnTopReplica/files/13853096/OnTopReplica-dump-20231025-1820.txt)
[OnTopReplica-dump-20231026-21.txt](https://github.com/LorenzCK/OnTopReplica/files/13853097/OnTopReplica-dump-20231026-21.txt)
[OnTopReplica-dump-20231028-2258.txt](https://github.com/LorenzCK/OnTopReplica/files/13853098/OnTopReplica-dump-20231028-2258.txt)
[OnTopReplica-dump-20231029-00.txt](https://github.com/LorenzCK/OnTopReplica/files/13853099/OnTopReplica-dump-20231029-00.txt)
[OnTopReplica-dump-20231029-05.txt](https://github.com/LorenzCK/OnTopReplica/files/13853100/OnTopReplica-dump-20231029-05.txt)
[OnTopReplica-dump-20231031-19.txt](https://github.com/LorenzCK/OnTopReplica/files/13853101/OnTopReplica-dump-20231031-19.txt)
[OnTopReplica-dump-20231111-150.txt](https://github.com/LorenzCK/OnTopReplica/files/13853102/OnTopReplica-dump-20231111-150.txt)
[OnTopReplica-dump-20231111-205.txt](https://github.com/LorenzCK/OnTopReplica/files/13853103/OnTopReplica-dump-20231111-205.txt)
[OnTopReplica-dump-20231111-206.txt](https://github.com/LorenzCK/OnTopReplica/files/13853104/OnTopReplica-dump-20231111-206.txt)
[OnTopReplica-dump-20231112-253.txt](https://github.com/LorenzCK/OnTopReplica/files/13853105/OnTopReplica-dump-20231112-253.txt)
[OnTopReplica-dump-20231112-2024.txt](https://github.com/LorenzCK/OnTopReplica/files/13853106/OnTopReplica-dump-20231112-2024.txt)
[OnTopReplica-dump-20231115-2355.txt](https://github.com/LorenzCK/OnTopReplica/files/13853107/OnTopReplica-dump-20231115-2355.txt)
[OnTopReplica-dump-20231120-314.txt](https://github.com/LorenzCK/OnTopReplica/files/13853108/OnTopReplica-dump-20231120-314.txt)
[OnTopReplica-dump-20231126-223.txt](https://github.com/LorenzCK/OnTopReplica/files/13853109/OnTopReplica-dump-20231126-223.txt)
[OnTopReplica-dump-20231221-231.txt](https://github.com/LorenzCK/OnTopReplica/files/13853110/OnTopReplica-dump-20231221-231.txt)
[OnTopReplica-dump-20231222-843.txt](https://github.com/LorenzCK/OnTopReplica/files/13853111/OnTopReplica-dump-20231222-843.txt)
[OnTopReplica-dump-20231224-252.txt](https://github.com/LorenzCK/OnTopReplica/files/13853112/OnTopReplica-dump-20231224-252.txt)
[OnTopReplica-dump-20231225-29.txt](https://github.com/LorenzCK/OnTopReplica/files/13853113/OnTopReplica-dump-20231225-29.txt)
[OnTopReplica-dump-20231227-041.txt](https://github.com/LorenzCK/OnTopReplica/files/13853114/OnTopReplica-dump-20231227-041.txt)
[OnTopReplica-dump-202118-44.txt](https://github.com/LorenzCK/OnTopReplica/files/13853115/OnTopReplica-dump-202118-44.txt)
[OnTopReplica-dump-202119-150.txt](https://github.com/LorenzCK/OnTopReplica/files/13853116/OnTopReplica-dump-202119-150.txt)
[OnTopReplica-dump-202121-032.txt](https://github.com/LorenzCK/OnTopReplica/files/13853117/OnTopReplica-dump-202121-032.txt)
[OnTopReplica-dump-202128-2043.txt](https://github.com/LorenzCK/OnTopReplica/files/13853118/OnTopReplica-dump-202128-2043.txt)
[OnTopReplica-dump-202128-2146.txt](https://github.com/LorenzCK/OnTopReplica/files/13853119/OnTopReplica-dump-202128-2146.txt)
[OnTopReplica-dump-202385-05.txt](https://github.com/LorenzCK/OnTopReplica/files/13853120/OnTopReplica-dump-202385-05.txt)
[OnTopReplica-dump-202385-185.txt](https://github.com/LorenzCK/OnTopReplica/files/13853121/OnTopReplica-dump-202385-185.txt)
[OnTopReplica-dump-202389-1947.txt](https://github.com/LorenzCK/OnTopReplica/files/13853122/OnTopReplica-dump-202389-1947.txt)
[OnTopReplica-dump-202391-29.txt](https://github.com/LorenzCK/OnTopReplica/files/13853123/OnTopReplica-dump-202391-29.txt)
[OnTopReplica-dump-202394-039.txt](https://github.com/LorenzCK/OnTopReplica/files/13853124/OnTopReplica-dump-202394-039.txt)
[OnTopReplica-dump-202395-033.txt](https://github.com/LorenzCK/OnTopReplica/files/13853125/OnTopReplica-dump-202395-033.txt)

**Comment by DivannKokos** [comment]
самый смешной баг репорт (?) который я видел пока что на гитхабе, продолжай в том же духе))
most funny bug report (?) that i've ever seen yet on github, keep up the good work))

**Comment by LorenzCK** [comment]
Hi @Wrascon,
thank you for the bug report(s)! This is a known issue that probably will not be fixed anytime soon, unfortunately. You can fix it by deleting the configuration file here:
```
C:\Users\zashi\AppData\Local\Lorenz_Cuno_Klopfenstein\OnTopReplica.exe_Url_rsssrdcbizpyqyetxsowclamfw3njd5s\3.5.1.0\user.config
```
This should reset OnTopReplica and let it start normally again.

Cheers!
