### ISSUE TITLE
Window randomly moved to x~=-28,000 y~=15 and now cant access ontopreplica at all on this computer no matter what I do

### ISSUE THREAD

**Issue by Flaming-Dorito** [LorenzCK/OnTopReplica#156]
So randomly my Ontop replica window dissapeared and now I can't get it back. It looks like it teleported to x= -28k somehow.
I can't open the settings to fix it cuz I need to click on the window to open Ontopreplica settings. 

I don't know how I can reset the window position. I have tried uninstalling and re-installing Ontopreplica but it keeps the previous window location somewhere in memory and idk where to find that.

Any help will be appreciated or else I won't be able to use Ontopreplica ever again since even reinstalling doesn't delete the settings and that's very sad.

I need to know how to completely reset ontopreplica so it doesn't remember the settings from a previous installation.

Or at least how to reset the window location please

Latest Log:
```13:21:40 Launching OnTopReplica v.3.5.1.0
13:21:40 Microsoft Windows NT 10.0.22631.0 detected, using support class OnTopReplica.Platforms.WindowsSeven
13:21:40 Platform support initialized
13:21:40 Restoring window at {X=-28358,Y=-15} size {Width=2566, Height=30} with chrome
13:21:40 Main form constructed
13:21:40 Entering application loop
13:21:40 Shell hook window registered successfully
13:21:40 Registered message pump processor OnTopReplica.MessagePumpProcessors.WindowKeeper
13:21:40 Registered message pump processor OnTopReplica.MessagePumpProcessors.HotKeyManager
13:21:40 Registered message pump processor OnTopReplica.MessagePumpProcessors.GroupSwitchManager
13:21:40 Registered message pump processor OnTopReplica.MessagePumpProcessors.FlashCloner
13:21:40 Main form shown
13:21:40 Applying command line launch parameters
13:21:40 Cloning window HWND 27136512 of class Chrome_WidgetWin_1
13:21:40 Setting new thumbnail
         HWND #27136512 (class Chrome_WidgetWin_1), region 
13:21:40 Unable to check for updates
         System.Net.WebException: The remote name could not be resolved: 'ontopreplica.codeplex.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at OnTopReplica.Update.UpdateManager.CheckForUpdateCallback(IAsyncResult result)
13:24:22 Main form closing
13:24:22 Deregistered shell hook window successfully
13:24:22 Main form closed
13:24:22 Last position before shutdown: {X=-28362,Y=-19}, size: {Width=2580, Height=44}
13:24:22 Persisting settings
13:24:22 Shutting down OnTopReplica```

**Comment by LorenzCK** [comment]
Hi @Flaming-Dorito: that’s weird, but the setting system in OnTopReplica is very wonky. Try typing the following string into any Windows Explorer address bar:

```%LOCALAPPDATA%\Lorenz_Cuno_Klopfenstein```

this should open the settings directory. There _might_ be more than one sub-directory, one per version you installed. You can either try to modify the settings from there, using any text editor, or you can delete everything and fully reset OnTopReplica.

Hope this helps!

**Comment by Flaming-Dorito** [comment]
I was able to reset the window to 0,0 in that file and then change the settings from there. Thanks so much!

Also, thanks for making this software! It's awesome

**Comment by LorenzCK** [comment]
Excellent!
