### ISSUE TITLE
Shortcut Locking window.

### ISSUE THREAD

**Issue by SourVenom** [LorenzCK/OnTopReplica#16]
It would be nice to have a shortcut that would lock the window in place and prohibit any interactions with it. So basically it would just display window content normally but mouse whouldn't interact with it whatsoever, instead it would treat space that OTR window occupies as if OTR was not there (untill shortcut is activated again).

**Comment by LorenzCK** [comment]
Sounds good. However, it sounds a bit like _click-through_ mode: since OTR ignores mouse input when this mode is enabled, it is effectively locked in place and cannot be moved. Are there other differences you had in mind?

**Comment by SourVenom** [comment]
I haven't used that option in a while (previously OTR window remained ~50% opaque, now it only does that while cursor hovers over it which is even better than what i proposed), seems to fit perfectly with what I meant. Thank you for pointing that out :)

**Comment by LorenzCK** [comment]
Great! 😃
