### ISSUE TITLE
Saving Region And Open It when Starts

### ISSUE THREAD

**Issue by cvetantokov** [LorenzCK/OnTopReplica#4]
Hello,
first to tell that this program is incredible.I am using to view a specific window ,in a specific region, I need when starts OnTopReplica to clone specific windows(alredy done this), in specific region , but it clones whole window, so my question is  Is it possible to be done when starts to clone the window in saved region ? I have done it when it starts to clone the window that i want but i cant make it to open and region.
Thanks in Advance.

**Comment by LorenzCK** [comment]
Hello @cvetantokov, thank you very much. I'm happy you find OnTopReplica useful!

It is possible to automatically setup OnTopReplica on launch using command line parameters. Use the command line to navigate to OnTopReplica's directory and
```
OnTopReplica.exe --help
```
will give you a full list of all available parameters.

For your use-case, you could use the following command:
```
OnTopReplica.exe --windowTitle="Opera" --region=100,100,300,200
```
This will clone the window with "Opera" in its title (my browser, for instance) and automatically crop the clone to a `300x200` pixel region, starting from the `X:100` `Y:100` point from top left.

Alternatively, you can also express the crop region in terms of padding from the external borders of the original window:
```
OnTopReplica.exe --windowTitle="Opera" --padding=100,200,300,400
```
This will crop the same browser window, using a region that is 100 pixels from the left border, 200 from the top, 300 from the right, and 400 from the bottom.

Hope this helps! :blush:

**Comment by cvetantokov** [comment]
Thanks for support . It worked . Again great program, good work.
