### ISSUE TITLE
3.5.1 installer requiring .net framework 4.7 but downloads 4.6.1

### ISSUE THREAD

**Issue by Spasticon** [LorenzCK/OnTopReplica#49]
Tried this with both the .exe and .msi installers. Both notify that they need .net framework 4.7 but then proceed to download .net framework 4.6.1

Installation cannot be completed unless .net framework is manually downloaded and installed.

**Comment by LorenzCK** [comment]
Thanks! Just updated the installer, which now links to the [.NET 4.7.2 Web installer](https://go.microsoft.com/fwlink/?linkid=863262).
