### ISSUE TITLE
Request: Make resizing possible while border is hidden or have a keyboard shortcut to toggle borders

### ISSUE THREAD

**Issue by Nizars** [LorenzCK/OnTopReplica#51]
I love this app but I just can't stand the sight of the white borders. 

I would like to use the app with the white borders hidden but still be able to resize the window now and then without having to go through a series of steps to do so.

Is it possible to make the border transparent? If not, is it possible to set a keyboard shortcut to quickly toggle the border?

Thanks in advance

**Comment by LorenzCK** [comment]
Hi @Nizars, glad you like the app!
Yes, the borders are pretty ugly, *especially* on Windows 10 (they are hideously asymmetrical as well). I am trying to rework this for the next version. A shortcut to toggle the border "chrome" sounds like a good idea. You can always quickly resize OnTopReplica using the mouse wheel while hovering over the window (mouse wheel up scales OTR up, mouse wheel down scales down).

**Comment by Nizars** [comment]
Oh my god! This is better than the keyboard shortcut! Thanks for letting me know! :)

**Comment by LorenzCK** [comment]
Great! OTR also needs better documentation, I'm afraid... 😉
