### ISSUE TITLE
how do I move my window after enabling click through?!!

### ISSUE THREAD

**Issue by pantojacamilla** [LorenzCK/OnTopReplica#55]
when I enable click through I'm not able to move my window to another position nor open the options menu is there a way to do it without closing and reopening the software?!

**Comment by LorenzCK** [comment]
Yes, although it is very poorly documented. You need to bring back focus to the OnTopReplica window: this can be done by clicking on the app's icon on the Task Bar or by switching to it via [ALT]+[TAB].
Let me know if this works.

**Comment by pantojacamilla** [comment]
Thanks man! 
It worked, you're the best.
