### ISSUE TITLE
not working when minimizing the window that is cloned ?

### ISSUE THREAD

**Issue by badplay** [LorenzCK/OnTopReplica#71]
i really dont know if it is normal

but when i clone a youtube tab and minimize the browser it stops and only show last thing on the tab 

hope you understand what i mean

so the browser have always be opened and not minimized is it right ?? alsow with ather programms ?

**Comment by LorenzCK** [comment]
Yes, this is unfortunately normal: minimized windows are not repainted by Windows for performance reasons. If you hover over the task bar, you will notice that minimized windows are not refreshed there either. I suggest you either move cloned windows behind another window or move it off-screen (moving the window to another virtual desktop should also be possible).
