### ISSUE TITLE
Cant run OTR

### ISSUE THREAD

**Issue by Jakemcandrew** [LorenzCK/OnTopReplica#76]
I cannot open OTR due to there being no .EXE file that I can directly run

I would like a guide on how to open OTR.

I am running on windows 10 
anyone else having the same odd issue?

**Comment by imlinus** [comment]
Hi Jake,

If you go to the "releases" tab in the repo, you'll find a URL to a .zip file (https://github.com/LorenzCK/OnTopReplica/releases/download/v3.5.1-fix/OnTopReplica-v3.5.1-fix.zip) that one includes both a .exe and a .msi that you can run 👍 

I hope that you enjoy this tool as much as I do!

Cheers,
