### ISSUE TITLE
Cloned window freezes when not visible

### ISSUE THREAD

**Issue by Iflail** [LorenzCK/OnTopReplica#90]
Just started having an issue with this after years of use and my only guess is the updated .net framework 4.8 . Anyhow whenever I try to use OnTopReplica for anything with video running (Youtube, Netflix, Twitch) the whole cloned window just goes white as soon as the cloned window is no longer visible. If there is a few pixels visible with other programs I'm using the cloned window works as intended.
![ontop replica issue](https://user-images.githubusercontent.com/57736005/68819971-9ffb3180-063e-11ea-809c-c06e7354a7b2.png)

**Comment by tazmaster** [comment]
Upon switching from source window to another window, Youtube, Netflix, Amazon Video, etc. all stop playing and goes to to a blank screen. This happens no matter if the source video is in full-screen mode or not.
![Capture1](https://user-images.githubusercontent.com/57738139/68822359-54548200-0656-11ea-9bfb-0aab0e48319b.JPG)
![Capture2](https://user-images.githubusercontent.com/57738139/68822363-574f7280-0656-11ea-9211-a46eda2f09e9.JPG)

**Comment by jBbL81** [comment]
started happening to me as well. i've been using OTR for years and never had any problems. i use this a lot so i need this to work. i reinstalled windows OS just now and same thing. figured out the problem -- chrome (for example) needs to be in full screen otherwise OTR will not work when it is not the active window.

test it yourself -- open a random youtube video and switch to small window. then switch to another window and OTR will display nothing. then change the youtube video to full screen and alt+tab to another window and OTR will now work as before.

hope it gets sorted out.

**Comment by tazmaster** [comment]
The only thing I can think of is that Windows update installed some files when I shut down my PC last night.

**Comment by jBbL81** [comment]
try another browser.

i just tested it on microsoft edge. twitch player is NOT full screen and edge browser is NOT full screen as well and OTR works perfectly.

maybe it's a chrome thing?

**Comment by jBbL81** [comment]
problem fixed in chrome!!! go here -- https://old.reddit.com/r/chrome/comments/dvpxio/chrome_video_automatically_turns_off_audio_plays/f7eok0i/

**Comment by tazmaster** [comment]
> problem fixed in chrome!!! go here -- https://old.reddit.com/r/chrome/comments/dvpxio/chrome_video_automatically_turns_off_audio_plays/f7eok0i/

This did indeed work! Thanks for pointing this out. :)

**Comment by Iflail** [comment]
Thanks a ton this fixed it for me as well!

**Comment by Ofangela** [comment]
The reddit fix (linked above by @tazmaster) worked for me! Here is the info thanks to u/WhateverIsFrei:

1. Go to chrome://flags/
2. Find #web-contents-occlusion
3. Set to disabled.

Hyperlink:
![image](https://user-images.githubusercontent.com/63659398/97119753-a025fd00-16e8-11eb-99ef-79eeba5ae057.png)

The setting to look for:
![image](https://user-images.githubusercontent.com/63659398/97119727-7240b880-16e8-11eb-9beb-662fa2bd2ec0.png)

**Comment by AlanJones94** [comment]
Thank you, managed to get it working!

**Comment by Flaming-Dorito** [comment]
Solution no longer works as chrome removed the #calculate-native-win-occulsion flag. Issue is back.

**Comment by jBbL81** [comment]
i got it to work again by following OPTION #3 here -- https://www.reddit.com/r/incremental_games/comments/rxcsjy/chrome_occlusion_problem_is_back_help_please/hwjzzo1/

**Comment by Flaming-Dorito** [comment]
In registry editor I cannot find the path to chrome. 

There is no "Google" under the "Policies" folder. I only see Adobe, Microsoft, Riot and Vmware. No google.

**Comment by jBbL81** [comment]
just follow the bottom part of the guide dude:

```
Or copy the following into a new Notepad document, save with a .reg extension and run

Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome]
"NativeWindowOcclusionEnabled"=dword:00000000
"WindowOcclusionEnabled"=dword:00000000
```

that's what i did. literally took 10 seconds.

just make sure chrome is closed before applying the registry fix.

**Comment by Flaming-Dorito** [comment]
Thank you so much! This worked like a charm.

**Comment by Shaarvin** [comment]
So Discord, whenever a friend webcams. I use ontopreplica, then go to google the discord webcam goes grey. It only does this with discord. using ontop for google or other games is fine. but not the other way. I did turned off exceleration on discord. idk how to fix this. if theirs a fix solution thank you.
